# Generated by Django 6.0.1 on 2026-02-02 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rm_last_assigned_at'),
        ('chat', '0003_message_message_type_messagemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.message')),
                ('rm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.rm')),
            ],
            options={
                'unique_together': {('message', 'rm', 'emoji')},
            },
        ),
    ]
