# Generated by Django 6.0.1 on 2026-02-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rm_last_assigned_at'),
        ('chat', '0004_message_is_deleted_messagereaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('message', 'rm')},
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message'], name='chat_messag_message_4e17fc_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['rm'], name='chat_messag_rm_id_417a40_idx'),
        ),
    ]
