# Generated by Django 6.0.1 on 2026-02-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_messagereaction_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='unread_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
