# Generated by Django 6.0.1 on 2026-02-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_conversation_unread_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
