# Generated by Django 6.0.1 on 2026-02-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_conversation_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='messagereaction',
            name='chat_messag_message_4e17fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagereaction',
            name='chat_messag_rm_id_417a40_idx',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_deleted',
        ),
        migrations.DeleteModel(
            name='MessageReaction',
        ),
    ]
